---
include:
  - board: nice_nano_v2
    shield: reviung34
  - board: nice_nano_v2
    shield: splitkb_aurora_sweep_left
  - board: nice_nano_v2
    shield: splitkb_aurora_sweep_right
  - board: nice_nano_v2
    shield: lancer
